using Bonfire.Builders;
using Microsoft.Extensions.DependencyInjection;

namespace Bonfire.DependencyInjection;

/// <summary>
/// Extension methods for registering Bonfire services with an <see cref="IServiceCollection"/>.
/// </summary>
public static class ServiceCollectionExtensions
{
    /// <summary>
    /// Registers a singleton <see cref="Bonfire"/> instance built by the supplied <see cref="BonfireBuilder"/> configuration.
    /// </summary>
    /// <param name="services">The service collection.</param>
    /// <param name="configure">A delegate that configures the <see cref="BonfireBuilder"/>.</param>
    /// <returns>The service collection for chaining.</returns>
    public static IServiceCollection AddBonfire(
        this IServiceCollection services,
        Func<IServiceProvider, BonfireBuilder, BonfireBuilder> configure)
    {
        services.AddSingleton(sp =>
        {
            var builder = new BonfireBuilder();
            builder = configure(sp, builder);
            return builder.Build();
        });

        return services;
    }

    /// <summary>
    /// Registers a singleton <see cref="Bonfire"/> instance built by the supplied <see cref="BonfireBuilder"/> configuration.
    /// </summary>
    /// <param name="services">The service collection.</param>
    /// <param name="configure">A delegate that configures the <see cref="BonfireBuilder"/>.</param>
    /// <returns>The service collection for chaining.</returns>
    public static IServiceCollection AddBonfire(
        this IServiceCollection services,
        Func<BonfireBuilder, BonfireBuilder> configure)
    {
        return services.AddBonfire((_, builder) => configure(builder));
    }

    /// <summary>
    /// Registers a transient service whose implementation type is generated by Bonfire at first resolution.
    /// A new instance is created for each resolution.
    /// Constructor dependencies of the generated type are resolved from the <see cref="IServiceProvider"/>.
    /// </summary>
    /// <remarks>
    /// Type generation is a blocking async-over-sync call. The generated type is not cached across
    /// resolutions; consider <see cref="AddBonfireSingleton{TService}"/> if only one instance is needed.
    /// </remarks>
    /// <typeparam name="TService">The service type (interface or abstract class) for Bonfire to implement.</typeparam>
    /// <param name="services">The service collection.</param>
    /// <returns>The service collection for chaining.</returns>
    public static IServiceCollection AddBonfireTransient<TService>(this IServiceCollection services)
        where TService : class
    {
        services.AddTransient(sp => CreateBonfireInstance<TService>(sp));
        return services;
    }

    /// <summary>
    /// Registers a scoped service whose implementation type is generated by Bonfire at first resolution.
    /// A new instance is created for each scope.
    /// Constructor dependencies of the generated type are resolved from the <see cref="IServiceProvider"/>.
    /// </summary>
    /// <remarks>
    /// Type generation is a blocking async-over-sync call.
    /// </remarks>
    /// <typeparam name="TService">The service type (interface or abstract class) for Bonfire to implement.</typeparam>
    /// <param name="services">The service collection.</param>
    /// <returns>The service collection for chaining.</returns>
    public static IServiceCollection AddBonfireScoped<TService>(this IServiceCollection services)
        where TService : class
    {
        services.AddScoped(sp => CreateBonfireInstance<TService>(sp));
        return services;
    }

    /// <summary>
    /// Registers a singleton service whose implementation type is generated by Bonfire on first resolution.
    /// The DI container ensures only a single instance is created and shared for all subsequent resolutions.
    /// Constructor dependencies of the generated type are resolved from the <see cref="IServiceProvider"/>.
    /// </summary>
    /// <remarks>
    /// Type generation is a blocking async-over-sync call that occurs once on first resolution.
    /// </remarks>
    /// <typeparam name="TService">The service type (interface or abstract class) for Bonfire to implement.</typeparam>
    /// <param name="services">The service collection.</param>
    /// <returns>The service collection for chaining.</returns>
    public static IServiceCollection AddBonfireSingleton<TService>(this IServiceCollection services)
        where TService : class
    {
        services.AddSingleton(sp => CreateBonfireInstance<TService>(sp));
        return services;
    }

    private static TService CreateBonfireInstance<TService>(IServiceProvider serviceProvider)
        where TService : class
    {
        var bonfire = serviceProvider.GetRequiredService<Bonfire>();
        var generatedType = bonfire.GenerateSubTypeAsync(typeof(TService)).GetAwaiter().GetResult();
        return (TService)ActivatorUtilities.CreateInstance(serviceProvider, generatedType);
    }
}
